---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes/custom-host
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sync.resourcesyncoperator.com
  resources:
  - resourcesyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sync.resourcesyncoperator.com
  resources:
  - resourcesyncs/finalizers
  verbs:
  - update
- apiGroups:
  - sync.resourcesyncoperator.com
  resources:
  - resourcesyncs/status
  verbs:
  - get
  - patch
  - update
