apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: resourcesyncoperator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ResourceSync is the Schema for the resourcesyncs API
      displayName: Resource Sync
      kind: ResourceSync
      name: resourcesyncs.sync.resourcesyncoperator.com
      statusDescriptors:
      - description: 'INSERT ADDITIONAL STATUS FIELD - define observed state of cluster
          Important: Run "make" to regenerate code after modifying this file'
        displayName: Conditions
        path: conditions
      version: v1alpha1
  description: This operator serves a very simple task, syncing between resources
  displayName: ResourceSync
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - Sync
  - Certificates
  - Secrest
  links:
  - name: Resourcesyncoperator
    url: https://resourcesyncoperator.domain
  maintainers:
  - email: eyalp700@gmail.com
    name: eyal
  maturity: alpha
  provider:
    name: Eyal
  version: 0.0.0
